### ISSUE TITLE
OK, *fine*, let’s go to Markdown

### ISSUE THREAD

**Issue by simoncozens** [commontype-standard/commontype#27]
Removing barriers to contribution is super important, and DocBook is one of them. Also prettier diffs.

**Comment by alerque** [comment]
Conversion to DocBook if somebody wants that output is much easier than collaborative editing in it!

What do you think about going with a modified superset of Markdown like Bikeshed? (Maybe comment on that in issue 25 linked above instead of here.)

Either way I can help with the conversion of existing content when we settle on what the target is to be.

**Comment by simoncozens** [comment]
Switching over to the bikeshed branch as master has implemented this.
